# Generated by Django 3.2.8 on 2021-11-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinion',
            options={'ordering': ['-nombre'], 'verbose_name': 'Opinion', 'verbose_name_plural': 'Opiniones'},
        ),
        migrations.AlterField(
            model_name='opinion',
            name='calificacion',
            field=models.ImageField(upload_to='opinion', verbose_name='Calificacion'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='imagen',
            field=models.ImageField(upload_to='opinion', verbose_name='Imagen de Perfil'),
        ),
    ]
